query_routing_task:
  description: >
    Analyze the user query: "{user_query}"
    
    Determine if this query should be handled as:
    1. ECHO - Questions about GT Guidelines, GT company policies, GT procedures, or GT-specific requirements
    2. AUDIT - Questions about audit methodologies, audit techniques, audit procedures, or general audit practices
    3. RESEARCH - Requires current external information, regulatory updates, or industry trends
    4. TRANSLATE - Requests translation of a document (PDF or DOCX) from one language to another
    
    Consider these factors:
    - Does it ask about GT company guidelines, GT policies, GT procedures, or GT-specific requirements? -> ECHO
    - Does it ask about audit methodologies, audit techniques, audit procedures, or general audit practices? -> AUDIT
    - Does it need current regulations, recent changes, or industry trends? -> RESEARCH
    - Does it request document translation (PDF/DOCX), document conversion, or language transformation? -> TRANSLATE
    - Does it require both internal and external information? -> RESEARCH
  expected_output: >
    A single word: either "ECHO", "AUDIT", "RESEARCH", or "TRANSLATE" followed by a brief explanation of your reasoning.
  agent: query_router

echo_task:
  description: >
    Answer the user query using GT Guidelines and Policy knowledge base: "{user_query}"
    
    Search the echo index for relevant GT company guidelines, policies, procedures, and GT-specific requirements
    that can answer this question. Focus on providing accurate, specific information from GT internal sources.
    
    If the query cannot be fully answered from GT sources, indicate what additional information might be needed.
  expected_output: >
    A comprehensive answer based on GT Guidelines and Policy documentation, including:
    - Direct answer to the query
    - Relevant GT policy references or document citations
    - Any limitations or additional information needed
    Formatted as markdown without '```'
  agent: echo_rag_agent

audit_task:
  description: >
    Answer the user query using audit methodology knowledge base: "{user_query}"
    
    Search the audit-iq index for relevant audit methodologies, techniques, procedures, and best practices
    that can answer this question. Focus on providing accurate, specific information from audit methodology sources.
    
    If the query cannot be fully answered from audit methodology sources, indicate what additional information might be needed.
  expected_output: >
    A comprehensive answer based on audit methodology documentation, including:
    - Direct answer to the query
    - Relevant methodology references or document citations
    - Any limitations or additional information needed
    Formatted as markdown without '```'
  agent: audit_rag_agent

research_task:
  description: >
    Conduct comprehensive research for the query: "{user_query}"
    
    Use web search to find current information about:
    - Recent regulatory changes or updates
    - Industry best practices and trends
    - Current compliance requirements
    - Emerging audit methodologies
    
    Focus on finding credible, up-to-date sources and synthesize the information into a coherent response.
  expected_output: >
    A detailed research report including:
    - Current information addressing the query
    - Key findings from credible sources
    - Recent developments or changes
    - Practical implications for audit practices
    - Source citations
    Formatted as markdown without '```'
  agent: audit_researcher

document_translation_task:
  description: >
    Translate the document (PDF or DOCX) specified in the request: "{user_query}"
    
    Extract the following information from the user request:
    - Document filename (can be just filename like "report.pdf" or full path)
    - Target language (language code like "es" or language name like "spanish")
    - Source language (if specified, otherwise use auto-detection)
    - Output file path (if specified, otherwise generate automatically)
    
    The system will automatically:
    - Search for the file in the Documents folder if only filename is provided
    - Handle both Mac and Windows file systems seamlessly
    - Convert language names to proper codes (spanish -> es, french -> fr, etc.)
    - Place translated files in the same folder with language suffix
    
    Use the document translation tool to convert the document while preserving:
    - Document formatting and layout
    - Images and graphics
    - Tables and structured content
    - Page numbering and headers/footers
    
    Ensure the translation maintains the professional quality needed for audit and compliance documentation.
  expected_output: >
    A summary report of the translation process including:
    - Confirmation of successful translation
    - Source and target languages used
    - Input and output file paths
    - File size information
    - Any warnings or issues encountered
    - Quality assurance notes about formatting preservation
    Formatted as markdown without '```'
  agent: document_translator
